---
apiVersion: v1
kind: Service
metadata:
  name: safecoin-devnet
  labels:
    app: safecoin-devnet
spec:
  ports:
    - port: 8328
      name: rpc
      protocol: TCP
    - port: 19900
      name: faucet
      protocol: TCP
  clusterIP: None
  selector:
    app: safecoin-devnet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: safecoin-devnet
spec:
  selector:
    matchLabels:
      app: safecoin-devnet
  serviceName: safecoin-devnet
  replicas: 1
  template:
    metadata:
      labels:
        app: safecoin-devnet
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: devnet
          image: safecoin-contract
          command:
            - solana-test-validator
            - --bpf-program
            - Bridge1p5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o
            - /opt/safecoin/deps/bridge.so
            - --bpf-program
            - B6RHG3mfcckmrYN1UhmJzyS1XX3fZKbkeUcpJe9Sy3FE
            - /opt/safecoin/deps/token_bridge.so
            - --bpf-program
            - NFTWqJR8YnRVqPDvTJrYuLrQDitTG5AScqbeghi4zSA
            - /opt/safecoin/deps/nft_bridge.so
            - --bpf-program
            - CP1co2QMMoDPbsmV7PGcUTLFwyhgCgTXt25gLQ5LewE1
            - /opt/safecoin/deps/cpi_poster.so
            - --bpf-program
            - metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s
            - /opt/safecoin/deps/spl_token_metadata.so
            # TODO(Victor): Temporary commented
            # - --bpf-program
            # - gMYYig2utAxVoXnM9UhtTWrt8e7x2SVBZqsWZJeT5Gw # Derived from pyth_program.json
            # - /opt/safecoin/deps/pyth_oracle.so
            - --bpf-program
            - P2WH424242424242424242424242424242424242424
            - /opt/safecoin/deps/pyth2wormhole.so
            - --bpf-program
            - Ex9bCdVMSfx7EzB3pgSi2R4UHwJAXvTw18rBQm5YQ8gK
            - /opt/safecoin/deps/wormhole_migration.so
            - --log
          ports:
            - containerPort: 8001
              name: gossip
              protocol: UDP
            - containerPort: 8003
              name: tpu
              protocol: UDP
            - containerPort: 8004
              name: tpufwd
              protocol: UDP
            - containerPort: 8000
              name: tvu
              protocol: UDP
            - containerPort: 8002
              name: tvufwd
              protocol: UDP
            - containerPort: 8006
              name: repair
              protocol: UDP
            - containerPort: 8007
              name: serverepair
              protocol: UDP
            - containerPort: 8328
              name: rpc
              protocol: TCP
            - containerPort: 8329
              name: pubsub
              protocol: TCP
            - containerPort: 9900
              name: faucet
              protocol: TCP
          readinessProbe:
            httpGet:
              port: rpc
              path: /health
            periodSeconds: 1
        - name: setup
          image: bridge-client-safecoin
          command:
            - /usr/src/safecoin/devnet_setup.sh
          readinessProbe:
            tcpSocket:
              port: 2000
            periodSeconds: 1
            failureThreshold: 300
